version: "2"
services:
  database:
    image: detonator-database
    environment:
     - MYSQL_DATABASE=detonator
     - MYSQL_ROOT_PASSWORD=sadetonator
     - MYSQL_USER=detonator
     - MYSQL_PASSWORD=duharaeyo
    command: ["--default-authentication-plugin=mysql_native_password", "--character-set-server=utf8"]
  webconsole:
    image: detonator-webconsole
    depends_on:
     - database
    ports:
     - "1776:80"
    privileged: true
